INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (1, 'Hipotesis de posibles necesidad de mercado', 1);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (2, 'Necesidades especificcas identificadas en el mercado', 1);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (3, 'Se establece la primera retoralimentacion del mercado', 1);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (4, 'Problema/necesidades confimadas de varios de clientes o usuarios', 1);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (5, 'Establecimiento de intereses y relaciones con los clientes', 1);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (6, 'Beneficios confirmados por la primeras pruebas del cliente', 1);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (7, 'Clientes en pruebas extendidas o primeras ventas de prueba.Pequeño número de usuarios activos.', 1);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (8, 'Primeras ventas comerciales y proceso de ventas implementado. Número sustancial de usuarios activos.', 1);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (9, 'Ventas generalizadas a esa escala. Gran número de usuarios activos con un crecimiento sustancial.', 1);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (10, 'Falta de competencias/recursos necesarios para verificar la idea. Poca percepción de las necesidades del equipo (típicamente un individuo). ', 2);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (11, 'Competencias limitadas en el lugar para comenzar a verificar la idea. Primera idea de competencias o recursos adicionales necesarios.', 2);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (12, 'Algunas de las competencias necesarias para verificar/desarrollar la idea. Competencias necesarias definidas (y plan para encontrarlas).', 2);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (13, 'Un campeón está presente con una idea clara de la dirección (inicio/otro camino). Varias competencias necesarias en su lugar plan iniciado para complementar."', 2);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (14, 'Equipo fundador inicial con las principales competencias y capacidades necesarias. El equipo acuerda la propiedad los roles los objetivos y las visiones."', 2);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (15, 'Equipo fundador complementario diverso y comprometido con todas las competencias y capacidades necesarias para comenzar a construir un negocio."', 2);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (16, 'Equipo y cultura que funcionan bien. Plan de crecimiento para expandir el equipo y desarrollar la organización a lo largo del tiempo.', 2);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (17, 'Organización profesional establecida (junta director ejecutivo gerencia personal)."', 2);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (18, 'Organización bien estructurada y de alto rendimiento en todos los niveles que se mantiene se desarrolla y funciona a lo largo del tiempo."', 2);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (19, 'Hipótesis nula o poco clara de la posible idea de negocio potencial de mercado y competencia."', 3);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (20, 'Primera hipótesis del posible concepto de negocio (en cualquier formato) e identificación del potencial general del mercado y la competencia.', 3);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (21, 'Descripción del modelo de negocio sostenible y mercado(s) objetivo incluida la competencia."', 3);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (22, 'Primeros cálculos que indican un modelo de negocio económicamente viable.Primera evaluación que indica sostenibilidad ambiental y social.', 3);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (23, 'Supuestos clave en el modelo de negocio sostenible probado en el mercado.', 3);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (24, 'Modelo de negocio sostenible completo probado en clientes socios proveedores (por ejemplo mediante ventas de prueba) los cálculos muestran viabilidad económica."', 3);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (25, 'Viabilidad del modelo de negocio sostenible (precios modelo de ingresos etc.) validado por las ventas comerciales iniciales."', 3);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (26, 'Las ventas y las métricas muestran que el modelo de negocio sostenible es viable', 3);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (27, 'Modelo de negocio sostenible que ha demostrado cumplir con las expectativas internas y externas sobre beneficios escalabilidad e impacto a lo largo del tiempo"', 3);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (28, 'Hipotetizar sobre sus posibles derechos de propiedad intelectual.', 4);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (29, 'Identificó diferentes formas de posibles DPI que tiene/crea. Se aclara la propiedad y puede utilizar los DPI pertinentes.', 4);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (30, 'Descripción de la posible clave de IPR con cierto detalle. Evaluación inicial del potencial para proteger los DPI clave.', 4);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (31, 'Confirmó que la protección de los DPI es posible y para qué. Decidió por qué proteger ciertos DPI (relevancia comercial).', 4);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (32, 'El borrador de la estrategia de IPR para crear valor comercial está en su lugar. Presentación de la primera solicitud/registro formal de derechos de propiedad intelectual clave.', 4);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (33, 'Primera estrategia completa de DPI implementada considerando diferentes DPI. Respuesta positiva en solicitudes/registros presentados.', 4);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (34, 'Solicitudes/registros formales presentados de DPI clave en países/regiones relevantes de acuerdo con la estrategia de DPI.', 4);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (35, 'Estrategia de DPI y prácticas de gestión totalmente implementadas. Solicitudes/registros formales presentados de DPI complementarios.', 4);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (36, 'Fuerte apoyo y protección de los DPI para las empresas. Protección de los DPI concedida y mantenida en los países pertinentes.', 4);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (37, 'No hay una descripción clara de las actividades de verificación inicial. No hay una visión clara de las necesidades iniciales de financiación y las opciones de financiación.', 5);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (38, 'Descripción de las actividades de verificación inicial. Necesidad de financiación definida y fuentes de financiación para los hitos iniciales.', 5);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (39, 'Financiamiento para el plan de verificación inicial asegurado.', 5);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (40, 'Financiamiento para el plan de verificación elaborado asegurado.', 5);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (41, 'Primer lanzamiento de financiación probado en una audiencia relevante. Definición de la necesidad de financiación a corto plazo y decisión sobre la estrategia de financiación.', 5);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (42, 'Presentación mejorada para la financiación probada en una audiencia relevante. Contactos iniciados con fuentes de financiación externas relevantes.', 5);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (43, 'Conversaciones iniciales con posibles fuentes de financiación externas. Presentación completa para financiación y material de apoyo listo.', 5);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (44, 'Discusiones a nivel de hoja de términos con una o varias fuentes de financiación externas que muestren un claro interés.', 5);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (45, 'Financiación asegurada para al menos 6-12 meses de operaciones. Sistema de pronóstico y monitoreo financiero completamente implementado.', 5);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (46, 'Resultados de investigación interesantes o idea de tecnología inicial identificada', 6);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (47, 'Concepto de tecnología y/o formulario de solicitud', 6);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (48, 'Prueba de concepto de funciones críticas y/o características en laboratorio', 6);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (49, 'Validación de tecnología en laboratorio', 6);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (50, 'Validación de tecnología en un entorno relevante', 6);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (51, 'Demostración de prototipo de tecnología en un entorno relevante', 6);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (52, 'Demostración de prototipo de tecnología en entorno operativo.', 6);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (53, 'Tecnología completa y demostrada en operaciones reales', 6);
INSERT INTO preguntas(id_pregunta, texto, id_categoria) VALUES (54, 'Tecnología completa y probada en operaciones reales a lo largo del tiempo.', 6);
